### ISSUE TITLE
Alternatively use the "Join" function from the str class

### ISSUE THREAD

**Issue by ahwagner** [johnegarza/chlamy-reference-genome#1]
See in codebase:

https://github.com/johnegarza/chlamy-reference-genome/blob/d10264e358d2640f3c498ba9dfc254f62db1e145/fosmid_pair_generation/index_dup_remover.py#L24

See str.join:

https://docs.python.org/3/library/stdtypes.html#str.join

**Comment by ahwagner** [comment]
@johnegarza please consider str.join here.

**Comment by johnegarza** [comment]
Resolved in commit https://github.com/johnegarza/chlamy-reference-genome/commit/efb561110f2563113af1211969dd1d5bd2e80c38

**Comment by johnegarza** [comment]
Further cleanup in commit https://github.com/johnegarza/chlamy-reference-genome/commit/9264165065d1831d8fd76df86eb834d6c2935033
