### ISSUE TITLE
use argparse

### ISSUE THREAD

**Issue by ahwagner** [johnegarza/chlamy-reference-genome#3]
consider the built-in module [argparse](https://docs.python.org/3/library/argparse.html) here.

https://github.com/johnegarza/chlamy-reference-genome/blob/d10264e358d2640f3c498ba9dfc254f62db1e145/delta_parser.py#L4-L9

**Comment by johnegarza** [comment]
Switched to argparse in commit https://github.com/johnegarza/chlamy-reference-genome/commit/ef6b175f158193e253e74da1a45c3055ff3cac90
