### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by ahwagner** [johnegarza/chlamy-reference-genome#4]
consider debugging using an IDE, such as [pyCharm](https://www.jetbrains.com/student/), or using the python interpreter.

https://github.com/johnegarza/chlamy-reference-genome/blob/d10264e358d2640f3c498ba9dfc254f62db1e145/delta_parser.py#L49-L59

**Comment by susannasiebert** [comment]
I've been using `pdb` for command line debugging. 
This adds a breakpoint:
```
import pdb
pdb.set_trace()
```

**Comment by johnegarza** [comment]
I'll take a look at the pdb module.
