### ISSUE TITLE
Use of a feature branch to make a pull request.

### ISSUE THREAD

**Issue by jasonwalker80** [johnegarza/chlamy-reference-genome#6]
@johnegarza you may want to consider future feature additions, bug fixes or really any update to the codebase on a branch. Using a branch is a convenient way to make pull requests and in a shared project modify code safely and independently with out committing to the master branch directly. 

There is a lot of good stuff in this blog on git branching, but a great takeaway would be the section on Feature Branches:
http://nvie.com/posts/a-successful-git-branching-model/

In the blog post, the example for a Feature Branch is based on the "develop" branch. A develop branch is nice particularly for larger projects, but a feature branch can also be made off of the master branch using similar git commands.

A few other git branching and git-flow resources:
https://jeffkreeftmeijer.com/git-flow/
https://danielkummer.github.io/git-flow-cheatsheet/

**Comment by johnegarza** [comment]
I've created a new branch, develop, off of the master for my current work. Once I have my core functionality complete, I'll experiment with further branches for features, bug fixes, etc.
